[package]
name = "electrs-json-rpc-macro"
version = "0.1.0"
authors = ["Andrew Cann <shum@canndrew.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.69"
quote = "1.0.9"
proc-macro2 = "1.0.26"
proc-macro-error = "*"

